    version: '3'
    services:
      setter_backend:
        build:
          context: .
          dockerfile: ./src/Dockerfile
        volumes:
          - ./setter:/usr/src/setter
        ports:
          - "8001:8995"
        depends_on:
          - postgres_db

      postgres_db:
        extra_hosts:
          - "host.docker.internal:host-gateway"
        image: postgres:15
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: seter
        ports:
          - "5432:5432"
        restart: always
        volumes:
          - ./setter/DATA/postgresDB:/var/lib/postgresql/storage
        networks:
          setter_net:
            ipv4_address: 192.168.0.2

      pgadmin:
        hostname: pgAdmin
        image: dpage/pgadmin4:6
        environment:
          PGADMIN_DEFAULT_EMAIL: root@pgadmin.com
          PGADMIN_DEFAULT_PASSWORD: root
        restart: always
        volumes:
          - ./setter/DATA/pgadmin:/var/lib/pgadmin4/storage
        ports:
          - "9090:80"
        depends_on:
          - postgres_db
        networks:
          setter_net:
            ipv4_address: 192.168.0.3

    volumes:
      postgresDB:
      pgadmin-data:
      setter_backend:

    networks:
      setter_net:
        ipam:
          driver: default
          config:
            - subnet: "192.168.1.0/24"
              gateway: 192.168.1.1